---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: kubernetes-backups
  namespace: backups
spec:
  # The PVC to be backed up
  sourcePVC: set me
  trigger:
    # Take a backup every hour
    schedule: "* * * * *"
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 14
    # Name of the Secret with the connection information
    repository: restic-config
    # Retention policy for backups
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    # Clone the source volume prior to taking a backup to ensure a
    # point-in-time image.
    copyMethod: Clone
