---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
data:
  limiter.toml: |
    # This configuration file updates the default configuration file
    # See https://github.com/searxng/searxng/blob/master/searx/limiter.toml

    [botdetection.ip_limit]
    # activate link_token method in the ip_limit method
    link_token = true

  settings.yml: |
    # see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
    use_default_settings: true
    server:
      # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
      limiter: true  # can be disabled for a private instance
      image_proxy: false
    ui:
      static_use_hash: true
    redis:
      url: redis://searxng-redis:6379/0
