---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: apps
spec:
  project: default

  source:
    repoURL: https://git.fascinated.cc/Fascinated/home-ops.git
    targetRevision: HEAD
    path: apps/
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
