---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyimg
  namespace: public-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyimg
  template:
    metadata:
      labels:
        app: flyimg
    spec:
      containers:
        - name: flyimg-container
          image: flyimg/flyimg:1.4.12
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: flyimg-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: flyimg
