---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flyimg
  namespace: public-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flyimg
  template:
    metadata:
      labels:
        app: flyimg
    spec:
      containers:
        - name: flyimg-container
          image: flyimg/flyimg:1.4.12
          securityContext:
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 250Mi
          volumeMounts:
            - name: flyimg-storage
              mountPath: /var/www/html/web/uploads
      volumes:
        - name: flyimg-storage
          persistentVolumeClaim:
            claimName: flyimg-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flyimg-pvc
  namespace: public-services
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: flyimg-service
  namespace: public-services
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: flyimg
