name: Check Kubernetes YAMLs

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.1"

      - name: Install kube-linter
        run: |
          go install golang.stackrox.io/kube-linter/cmd/kube-linter@latest

      - name: Scan yaml files with kube-linter
        run: |
          kube-linter lint ./apps
