---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: public-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:2024.9.23-6be56aee1
          ports:
            - containerPort: 8080
          env:
            - name: SEARXNG_BASE_URL
              value: "https://search.fascinated.cc"
            - name: SEARXNG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: searxng-secret
                  key: secret_key
          volumeMounts:
            - name: searxng-config-volume
              mountPath: /etc/searxng
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: searxng-config-volume
          configMap:
            name: searxng-config
