kind: Service
apiVersion: v1
metadata:
  name: cdn-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: internal ip
  ports:
    - name: http
      port: service port
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cdn-external-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`example.com`)
      kind: Rule
      services:
        - name: cdn-external
          port: service port
  tls:
    secretName: example.com
