kind: Service
apiVersion: v1
metadata:
  name: sentry-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.50.36
  ports:
    - name: http
      port: 8000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sentry-external-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`glitchtip.fascinated.cc`)
      kind: Rule
      services:
        - name: sentry-external
          port: 8000
  tls:
    secretName: fascinated-cc
