---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fascinated-cc
  namespace: traefik
spec:
  secretName: fascinated-cc
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.fascinated.cc"
  dnsNames:
    - "fascinated.cc"
    - "*.fascinated.cc"
