---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mcutils-xyz
  namespace: traefik
spec:
  secretName: mcutils-xyz
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.mcutils.xyz"
  dnsNames:
    - "mcutils.xyz"
    - "*.mcutils.xyz"
