kind: Service
apiVersion: v1
metadata:
  name: main-site-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.50.209
  ports:
    - name: http
      port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: main-site-external-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`fascinated.cc`)
      kind: Rule
      services:
        - name: main-site-external
          port: 3000
  tls:
    secretName: fascinated-cc
