kind: Service
apiVersion: v1
metadata:
  name: mc-tracker-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.3.76
  ports:
    - name: http
      port: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mc-tracker-external-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`mc-tracker.fascinated.cc`)
      kind: Rule
      services:
        - name: mc-tracker-external
          port: 3000
  tls:
    secretName: fascinated-cc
