---
apiVersion: v1
kind: Service
metadata:
  name: searxng-redis
  namespace: public-services
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: searxng-redis
