---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - ./notification/sealed-secret.yaml
  - ./notification/reciever.yaml
  - ./notification/ingress.yaml
