---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-secret
  namespace: flux-system
spec:
  encryptedData:
    token: AgB9gxfRBYdK3njhBAyXkKsFDSxncYLfO33bvV4Rq7hu4H6OM43xseXveMoSN5+Bw9gvjoaIkn/2Z7pUXNCIUwzG+JAtkDDyY25Xkmu53FN96f3ZUFBQyvtPcB3WTai3spki8GABqLUUkRFX3j7j+hBKLLdryKpkv77OSs/rh0K6V+LhtDjedSW+dKaywPA2kwf1jaX4T675fZpe0h5xpiV1KWO+mHyAmF03CgCC2LvnpCze1/6ZToU6EC+hETe2W6r3fDMxffnkggDgDO0hGy6py4ID00TFXd23dMHu/72caUUgFZGgKTkCF5/+AvOPNoVAaZSrs1V9xPPljYyCzDTucV8O7TfrG6tvsyPG74wU+y9R1OAbq/ZWBh8grMB8zfRHNKMbpGnCphcnB98vkZLQXAnlWYpCJOmerkQYBxiMs3l6XBbDPURuyO2/xOJe70XXDQ7BPA7ZsCilNQNSm+xY9U0Uf8g9oycNBhFoy96+b3VMy7VvAl0smsBPu4VuUwGxAJTftAmqT6lBFoordynEcUiL+q/xph7gKEZj6JQtNibrw5p8k1V8MreoWZe2DmeelgDvZcT7QpPgrHDvbCKNeHM2xFlOzgemBK8+/+Qcr9gZAJGQKE8ppUssD5zDECzk76A2mZ7/tJkGQFaFrC5zh7WDnpMfdXDkQac5e6hKFDAvuBckfgcLok8AAMlCeQgDcdwjlnrGXs1ZFYbvf73gIoAJknB9WZ44tM0I7Um3nzlqGXn5GF2S
  template:
    metadata:
      creationTimestamp: null
      name: notification-secret
      namespace: flux-system
    type: Opaque
