---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-fascinated-cc
  namespace: traefik
spec:
  secretName: local-fascinated-cc
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.fascinated.cc"
  dnsNames:
    - "*.local.fascinated.cc"
