kind: Service
apiVersion: v1
metadata:
  name: plex-external
  namespace: traefik
spec:
  type: ExternalName
  externalName: 10.0.0.235
  ports:
    - name: http
      port: 32400
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-external-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`plex.fascinated.cc`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
        - name: compress
          namespace: traefik
      services:
        - name: plex-external
          port: 32400
  tls:
    secretName: fascinated-cc
