---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
  - namespace.yaml
  - traefik.yaml
  #- ./external-services
  # for some stupid fucking reason kustomize doesn't support wildcards or globs?!?!?!??!?
