---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  template:
    spec:
      containers:
        - name: traefik
          args:
            - "--entryPoints.web.address=:8000/tcp"
            - "--entryPoints.websecure.address=:8443/tcp"
            - "--ping=true"
            - "--global.sendanonymoususage=false"
            - "--global.checknewversion=false"
            - "--serversTransport.insecureSkipVerify=true"
            - "--log.level=INFO"
            - "--providers.kubernetescrd"
            - "--providers.kubernetescrd.allowCrossNamespace=true"
            - "--providers.kubernetescrd.allowExternalNameServices=true"
            - "--providers.kubernetesingress.allowCrossNamespace=true"
            - "--providers.kubernetesingress.allowExternalNameServices=true"
